sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Ok1VOw5zdkBQQe0ETJfdkuff42XNBm5yW5h45rtX/y3bP1rpWE5rLF0QoDbvBHAMN6RStwM5T/ecsvzvg5WCZ6+4P+/IfnKkEGAyvLtA6bWCJpniJfzCCMrc5aVn3AuxnINidHU3JNkbcx7KNgKpwZMWP1Iv1Jukw7Nv7LYJ6wZXiiyg+Qy0MrHQcdeu3D/cT2hTV4QF+TCMixxApztKvh8plOizwKW2L8/ux54NVRLNruLFaGc0jatt6G4DjpcQ8PPSwHQD+YdpuiVsLX+1KEYBvJ7gLfhg4HRRwGsN51ey/pMgA2Znz0QYfNp+YoGXT7XtALNECpMYeFg5rAwIo+f4mEtv27Ta09kq+MvUsgTJIZvKlDzh1oi+LAMwUHgfLYjevyuZh+vJdv44/XWCbXzbPoyfP4mdUaz9RkdU85bxP9r5l1c7tuqfpDhzolQ8AHIym10k+9MloHLxQItLPM9hTbh0pIz6a363gMdCh73iYmH6IHRLMJjUZGYEatHEEzDG91BdDRgp0Clhy+nr74MYtHCCKwYSS1rcNVyfMlIBsDhXYJD/4CtD5Wc5IKpYdtdaxMaue7WiYBw/nrkCHbNcDNznTQqFVGpMF1hRMCsovISqrWIRPg1iFRZUnt401xuA+pZMHWL+ywEMO3zBLV86aOs/Je9vYVSIitYzJiE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: NyCxtWTnsGAv9B9cB/wFaW91HejAcaqemz6Hgq1zG4YpCioOBkv//cPfRR+BKcw4Um/Z48EDVqEAX6TpJ3DP+3y/s6mzeZ4LeLX0nVRc+uy3yQ6rHk/3N51/J4Dx/34Km4a3v7kzN3P7Id9oXKVFwRJvMtKmqd7j/EyHhqjOGQmnxeWVMn1iTcsyIh/SP60XsWzaUNq3xe8vL9+u4XzyxBeEI52M7pE3PbzvFyHpVCJypdDGFbdoC1GSyuhDqkRbmS6KRJ8FutrcXw/1v9m/FAKK7nNspEGDFnfVH7CSOIEWFCcfC38Tq6yg1PIhpiuKLS+hA4w/O3alCWfZPMcrTNh6KRr9wjxh1XI06iMcvubFMCh87SjHzFumk7mdUA1CYkMzlwckPcCRY3M0VB1RenOnw3009YAbutgcgJwpV6U/6g2i4gFfS/eZ9c0MgPox77f+Asibjcnmk93WNE2y1Ox3wn1hhX+la4NWyeRUDXR4WbAhB6orjyWcBJuAE4MOLIqHRMGjwDx8G7EB27EzSSu6FMCiY5TYzrFx3cDY8gu2lDYQxO13BC+o1NmZK3xZNP6rcaSqsPfHEcuRg9YNKzFTYwyf/0DXFbc63SVhK/aPfZ3d+0gwp+mSn3z5lU5xw0yEAoH5jUTq/2MzirZhZIRNirKpmlq/HdjxwRAXTIs=
